version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  mongo_seed:
    build:
      context: ./mongo_seed
      dockerfile: Dockerfile

    depends_on:
      - mongodb_container

  web:
    build:
      context: .
      dockerfile: ./Telemetry/Dockerfile
    restart: always
    ports:
      - 7256:443
      - 5196:80
    depends_on:
      - mongodb_container
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongodb_aspnet
  #   depends_on:
  #     - mongodb_container
