version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_aspnet
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    # volumes:
    #   - mongodb_data_container:/data/db

  web:
    build:
      context: .
      dockerfile: ./Telemetry/Dockerfile
    restart: always
    # ports:
    #   - 5196:80
    #   - 7256:443
    environment:
      - "ConnectionStrings:MongoDb=mongodb://mongodb_aspnet:27017/appdb"
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - mongodb_container
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
      #- ~/.aspnet/https:/https:ro
    # links:
    #   - mongodb_container
# volumes:
#   - mongodb_data_container
